[zh-cn]
  title = "MtF.wiki"
  languageName = "简体中文"
  weight = 1
  contentdir = "content/zh-cn"

[zh-hant]
  title = "MtF.wiki"
  languageName = "繁體中文"
  weight = 1
  contentdir = "content/zh-hant"

[ja]
  title = "MtF.wiki"
  languageName = "日本語"
  weight = 5
  contentdir = "content/ja"

[en]
  title = "MtF.wiki"
  languageName = "English"
  weight = 2
  contentdir = "content/en"

[es]
  title = "MtF.wiki"
  languageName = "Español"
  weight = 3
  contentdir = "content/es"
