name: 报告新的 SRS 医生
description: 报告新的 SRS 医生
labels: ["srs"]
body:
  - type: markdown
    attributes:
      value: 感谢您的报告，请根据该表单填充必要信息。
  - type: input
    id: hospital-name
    attributes:
      label: 医院名称
      description: 该医院的名字全称
    validations:
      required: true
  - type: input
    id: doctor-name
    attributes:
      label: 医生姓名
      description: 该医生的名字
    validations:
      required: true
  - type: textarea
    id: prerequisite
    attributes:
      label: 前置条件
      description: 该医院进行该项手术的前置条件列表
    validations:
      required: true
  - type: textarea
    id: fee
    attributes:
      label: 费用构成
      description: 进行 SRS 所需费用
    validations:
      required: true
  - type: textarea
    id: caveats
    attributes:
      label: 注意事项
      description: 您在面诊时遭遇的情况
    validations:
      required: true
  - type: textarea
    id: proof
    attributes:
      label: 证明样式
      description: 您已获得的证明或假条/病历扫描件（请直接将文件拖动到文本框进行上传）
  - type: checkboxes
    id: license
    attributes:
      label: 以 CC-BY-SA 4.0 协议分发
      description: 本站采用 [CC-BY-SA 4.0](https://creativecommons.org/licenses/by-sa/4.0/deed.zh-Hans) 协议分发内容
      options:
        - label: 我同意以 CC-BY-SA 4.0 协议分发
          required: true
