name: 报告新的学校
description: 报告新的学校
title: "学校："
body:
  - type: markdown
    attributes:
      value: 感谢您的报告，请根据该表单填充必要信息。
  - type: input
    id: campus-name
    attributes:
      label: 学校名称
      description: 该学校的名字全称
    validations:
      required: true
  - type: input
    id: address
    attributes:
      label: 地址位置
      description: 该学校的地理位置
    validations:
      required: true
  - type: checkboxes
    id: labels
    attributes:
      label: 标签
      options:
        - label: LGBT+ 友善
        - label: 能使用“易性证”免除体育测试
        - label: 教务协助“变更学历”
        - label: 校医提供”性激素六项“服务
        - label: 无性别厕所
        - label: 存在其他跨性别
  - type: textarea
    id: general
    attributes:
      label: 现状梗概
      description: 您在学校就读时遭遇的问题
    validations:
      required: true
  - type: checkboxes
    id: license
    attributes:
      label: 以 CC-BY-SA 4.0 协议分发
      description: 本站采用 [CC-BY-SA 4.0](https://creativecommons.org/licenses/by-sa/4.0/deed.zh-Hans) 协议分发内容
      options:
        - label: 我同意以 CC-BY-SA 4.0 协议分发
          required: true
