blank_issues_enabled: true

contact_links:
  - name: RLE.wiki
    url: https://github.com/mtf-wiki/RLE-wiki/issues/new/choose
    about: RLE.wiki
  - name: kuaer.club
    url: https://github.com/mtf-wiki/kuaer.club
    about: 跨性别导航 kuaer.club
